### ISSUE TITLE
where I can download pretrained resnet-101 in tensorflow version

### ISSUE THREAD

**Issue by ZhuFengdaaa** [mfigurnov/sact#2]
The code imagenet_train.py needs a pretrained resnet-101. However, Kaiming He just provide the prototxt and weights in Caffe version.

**Comment by mfigurnov** [comment]
I'll publish the pretrained ResNet-101 as soon as I get access to it. It might take a couple of days, sorry about that. Do you need any other model weights? In the meantime, you can run imagenet_train.py without specifying the `finetune_path` argument. In this case, ACT/SACT model is trained from scratch and you don't need any pretrained weights. The results will be a bit worse than with the two-stage training, though.

**Comment by mfigurnov** [comment]
You can also try the ResNet v2 101 weights from [Slim](https://github.com/tensorflow/models/tree/master/slim#pre-trained-models). I can't check at the moment, but I think they should be compatible with this repo's code.

**Comment by ZhuFengdaaa** [comment]
@mfigurnov Slim works. Thank you very much.

**Comment by mfigurnov** [comment]
@ZhuFengdaaa I've published the ResNet v2 101 model that we used as an initialization for the ACT/SACT models: https://s3.us-east-2.amazonaws.com/sact-models/imagenet_101.tar.gz . My server with a copy of ImageNet broke down, so I couldn't check the model, but I hope it works for you :)
