### ISSUE TITLE
How to get the feature maps in your programs

### ISSUE THREAD

**Issue by youngfly11** [mfigurnov/sact#4]
Hi, recently i wanna visualize some intermediate feature maps in your programs.  I use some way like 
sess =  tf.Session()  , sess.run(images),  {images are the tensor in cifar_main.py file}. It seems that it does not work, i can not convert the images tensor to numpy.  
Do you  have any idea to get some intermediate feature maps?

**Comment by mcollinswisc** [comment]
Can you modify your visualization code in some way to pass the intermediate feature map you're after to as another argument to the sess.run(...) call? That could give you the right numpy array.

**Comment by youngfly11** [comment]
Thanks for your comment. 

`def evaluate():
   g = tf.Graph()
   with g.as_default():
   data_tuple = cifar_data_provider.provide_data(FLAGS.split_name,
                                                  FLAGS.eval_batch_size,
                                                  dataset_dir=FLAGS.dataset_dir)
   images, _, one_hot_labels, num_samples, num_classes = data_tuple

   print(type(images))   ## here images is tensor type
   print('++++++++++++++++++++++++++++++++')
   Argu = images
   sess = tf.Session()
   argu = sess.run(Argu)
   print(type(argu))
   print("+++++++++++++++++++++++++++++++++")`
I have tried as you said, but it still does not work,  it alerts me that i have built a **empty session**. I can not handle this.
