### ISSUE TITLE
Cifar-10 global average pooling

### ISSUE THREAD

**Issue by ahyunSeo** [mfigurnov/sact#7]
In imagenet_model you defined resnet_v2 with global_pool,
is there any reason that cifar model doesn't contain global average pooling?
Am I missing something?
or the part
https://github.com/mfigurnov/sact/blob/6c45317228705cc6a0b27c48574ead08e7dfccda/cifar_model.py#L86
is doing what I am looking for?

**Comment by mfigurnov** [comment]
The global average pooling for CIFAR is done on this line: https://github.com/mfigurnov/sact/blob/master/cifar_model.py#L134

**Comment by ahyunSeo** [comment]
Thanks!
