### ISSUE TITLE
Working with ImageNet dataset, no data

### ISSUE THREAD

**Issue by anki54** [mfigurnov/sact#9]
Hi, First of all great paper, i am trying to run the scripts to evaluate with ImageNet data set, I am not able to get any data from the URL, 'https://raw.githubusercontent.com/tensorflow/models/master/inception/inception/data/'.
Also the link to prepare the ImageNet Dataset in TF-Slim format under 'Instructions' (https://github.com/tensorflow/models/tree/master/inception#getting-started) gives 404. 

Any help would be appreciated. 

regards,
anki

**Comment by mfigurnov** [comment]
Thank you for your interest in the paper! It looks like the paths have changed slightly. I have updated the README and the script, please try again and see if it works now.

**Comment by anki54** [comment]
Awesome. Thanks a ton.
